# local:
#   {{- include "launchpad.values-local" . | merge (lookup "file" "values-local.yaml") }}

# azure:
#   {{- include "launchpad.values-azure" . | merge (lookup "file" "values-azure.yaml") }}

# onprem:
#   {{- include "launchpad.values-onprem" . | merge (lookup "file" "values-onprem.yaml") }}

# aws:
#   {{- include "launchpad.values-aws" . | merge (lookup "file" "values-aws.yaml") }}

# gcp:
#   {{- include "launchpad.values-gcp" . | merge (lookup "file" "values-gcp.yaml") }}

# Default values for launchpad.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  #registry: puppysdacr.azurecr.io
  repository: pupsdacr.azurecr.io/stardog/pup-launchpad
  tag: "1.0"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # runAsNonRoot: true
  # runAsUser: 1000
  # readOnlyRootFilesystem: true


service:
  type: ClusterIP
  port: 80

jwt:
  enabled: false

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: FRIENDLY_NAME
    value: "Stardog Applications"
  - name: BASE_URL
    value: "http://localhost:8080"
  - name: SECURE
    value: "false"
  - name: K8S_DEPLOYMENT
    value: "true"
  - name: STARDOG_INTERNAL_ENDPOINT
    value: http://localhost:5820/
  - name: STARDOG_EXTERNAL_ENDPOINT
    value: http://localhost:5820/

