apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "launchpad.fullname" . }}
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "launchpad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "launchpad.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "launchpad.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: COOKIE_SECRET
              value: {{ randAlphaNum 24 | quote }}
            {{- if .Values.jwt.enabled }}
            - name: JWK_LOCATION
              value: "/jwt"
            {{- end }}
            {{- range $.Values.env }} 
            - name: {{ .name }}
              value: {{ .value | quote}}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.jwt.enabled }}
          volumeMounts:
          - name: {{ .Values.jwt.secretName }}
            mountPath: "/jwt/cert.key"  
            subPath: cert-key.key  
          - name: {{ .Values.jwt.secretName }}  
            mountPath: "/jwt/pubkey.pub" 
            subPath: public-key.pub
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.jwt.enabled }}
      volumes:
      - name: {{ .Values.jwt.secretName }}
        secret:
          secretName: {{ .Values.jwt.secretName }}
  {{- end }}
